### ISSUE TITLE
RBQFetchedResultsController doesn't appear to work with Swift 

### ISSUE THREAD

**Issue by mgleason** [Roobiq/RBQFetchedResultsController#3] opened 2015-04-03 20:20 UTC
I added a pull request with the Example App rewritten in Swift.  When you run it, the tableview is empty (and numberOfSections returns 0...) - though the TestObject in the Realm Database contains 1001 records.

**Comment by bigfish24** [comment] 2015-04-03 20:49
Copying over my comment from the pull request:

Ok well the issue is that Swift Classes are identified with a different string than Obj-C classes. So the logic is broken because the FRC represents the original RLMObject in its cache by storing the NSString of the Class name. It then reproduces the object by calling the function NSClassFromString() to get the Class to call the RLMObject class method to retrieve the object by primary key.

So the problem is that the class name it is storing is "TestObject" versus "RBQFetchedResultsControllerSwiftExample.TestObject"

I recalled noticing this when reviewing Realm's code because they have two methods to identify and clean up Swift classes in RLMSwiftSupport

So I will need to rework the logic to handle this issue since it touches the RBQFetchRequest and RBQFRC.

**Comment by Brisdo** [comment] 2015-04-03 21:25
Ahh, great insight.  Thanks Adam!

**Comment by bigfish24** [comment] 2015-04-07 17:34
Have a fix that will be coming in the next version to add support for Swift... see for more details: https://github.com/Roobiq/RBQFetchedResultsController/pull/2

**Comment by bigfish24** [comment] 2015-04-07 18:56
Ok this issue should be fixed in v1.7.4: https://github.com/Roobiq/RBQFetchedResultsController/releases

**Closed by bigfish24** 2015-04-07 18:56 UTC
Labels: bug
