### ISSUE TITLE
support for Realm Swift (with Object as the base model class instead of RLMObject)

### ISSUE THREAD

**Issue by triage** [Roobiq/RBQFetchedResultsController#29] opened 2015-06-29 19:44 UTC
Hey there
It seems that the examples and RBQFetchRequest are dependent upon using Realm's Objective-C framework, where `RLMObject` is the base class for model classes, whereas in Realm for Swift, the base class is simply `Object`. (I get assertion failures for example when trying to use `Object`).

I'm happy to work on this, but before I dive in, would anybody be able to offer any guidance about what specifically would need to be done to be as non-invasive as possible? Is this already in the works?

Thank you

**Comment by bigfish24** [comment] 2015-06-29 22:41
I looked into this but the type safety with the Swift API makes this not possible at the moment. You can't store the class name of the model object and later perform a query using NSClassFromString(). Instead the proper way to do it is to use Realm's "dynamic" interface. This allows you to perform queries with just the class name string directly. The issue is that by default this functionality is in a private header. So it is possible but it would require a fork of the Realm framework. I was holding off because I am working to get the dynamic API released.

**Comment by triage** [comment] 2015-06-29 23:01
thank you, @bigfish24

**Comment by bigfish24** [comment] 2015-06-30 00:04
No problem, hopefully won't take too long!

**Comment by bigfish24** [comment] 2015-07-15 14:39
Just wanted to let you know that I am having discussion internally at Realm to discuss the approach we want to go with in terms of supporting components built to work with Realm Swift. From this then I hope to adjust the framework to support it.

**Comment by triage** [comment] 2015-07-15 15:34
man that's great news ... thank you so much, @bigfish24.

**Comment by bigfish24** [comment] 2015-08-04 22:35
I have preliminary support for `RealmSwift` ready to go in this PR: https://github.com/Roobiq/RBQFetchedResultsController/pull/34

However, I can't merge it yet because it uses a custom build of `Realm`: https://github.com/realm/realm-cocoa/pull/2213 that makes public dynamic API methods/functions to enable better interoperability with `Realm` and `RealmSwift`.

**Comment by siuying** [comment] 2015-08-13 14:30
:+1:

**Comment by bigfish24** [comment] 2015-08-27 14:42
The PR: https://github.com/Roobiq/RBQFetchedResultsController/pull/34 has been merged. I will be releasing this today.

**Comment by azfx** [comment] 2015-08-27 19:12
Awesome!

**Comment by bigfish24** [comment] 2015-08-27 21:07
Support now added! Add this to your podfile:
```
use_frameworks!

pod 'SwiftFetchedResultsController'
```

**Closed by bigfish24** 2015-08-27 21:07 UTC
Labels: enhancement

**Comment by bigfish24** [comment] 2015-08-27 21:25
Check out the example project to see how it works. Very similar to the Objc-C API.

**Comment by triage** [comment] 2015-08-28 03:14
thank you @bigfish24!

**Comment by bigfish24** [comment] 2015-08-28 03:24
No problem! I plan to write additional documentation/rework the README, but please let me know if you run into any issues.
